In [3]:
out = []

for x in range(1,11):
    out.append(x**2)

In [4]:
print(out)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [5]:
for x in out:
    print(x)

1
4
9
16
25
36
49
64
81
100


In [24]:
seq = (1,2,3,4,5,6,7,8,9,10)

def my_func(var):
    return var*2

my_func(3)

6

In [25]:
list(map(my_func,seq))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [26]:
list(map(lambda var:var**3,seq))

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [27]:
list(map(lambda var:var%2 == 0,seq))

[False, True, False, True, False, True, False, True, False, True]

In [28]:
seq_list = list(filter(lambda var:var%2 == 0,seq))
seq_list

[2, 4, 6, 8, 10]

In [6]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(3)

array([0.89465093, 0.18323161, 0.2222026 ])

In [38]:
ranarr = np.random.randint(0,100,9)

In [51]:
arr = ranarr.reshape(3,3)
arr

array([[56, 26, 43],
       [77, 69, 24],
       [94, 57, 63]])

In [52]:
arr.min()

24

In [53]:
arr.max()

94

In [54]:
arr.argmax()

6

In [55]:
arr.shape

(3, 3)

In [58]:
arr = np.arange(5,50,5)

In [59]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [62]:
arr_2d = arr.reshape(3,3)

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
arr_2d[0,2]

15

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [72]:
arr_2d[:2,:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr % 2 == 0
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [83]:
arr[bool_arr]

array([ 2,  4,  6,  8, 10])

In [84]:
arr[bool_arr] > 5

array([False, False,  True,  True,  True])

# Pandas

In [85]:
import numpy as np
import pandas as pd

In [93]:
labels = ['a','b','c','d']
my_list = [10,20,30,40]
arr = np.array(my_list)
this_dist = {'a':10,'b':20,'c':30,'d':40}

In [94]:
pd.Series(my_list,labels)

a    10
b    20
c    30
d    40
dtype: int64

In [95]:
pd.Series(arr,labels)

a    10
b    20
c    30
d    40
dtype: int32

In [97]:
pd.Series(labels)

0    a
1    b
2    c
3    d
dtype: object

In [99]:
ser1 = pd.Series([70,65,46,73],['english','hindi','SST','science'])
ser1

english    70
hindi      65
SST        46
science    73
dtype: int64

In [100]:
ser2 = pd.Series([70,65,89,73],['english','hindi','sanskrit','science'])
ser2

english     70
hindi       65
sanskrit    89
science     73
dtype: int64

In [105]:
ser1[1]

65

In [106]:
ser1 + ser2

SST           NaN
english     140.0
hindi       130.0
sanskrit      NaN
science     146.0
dtype: float64

# DataFrames

In [108]:
rows = ['w','x','y','z']
cols = ['a','b','c','d']

In [120]:
df = pd.DataFrame(np.random.randn(4,4),rows,cols)
df

a         b         c         d
w  0.760020 -0.300510 -0.023017  0.147757
x  0.226229  0.730843  0.495561  0.053208
y  1.550351  0.347815  0.113641  1.080122
z -0.397774 -0.955076 -1.013538  0.594190

In [121]:
type(df['a'])

pandas.core.series.Series

In [122]:
df[['a','d']]

a         d
w  0.760020  0.147757
x  0.226229  0.053208
y  1.550351  1.080122
z -0.397774  0.594190

In [123]:
df

a         b         c         d
w  0.760020 -0.300510 -0.023017  0.147757
x  0.226229  0.730843  0.495561  0.053208
y  1.550351  0.347815  0.113641  1.080122
z -0.397774 -0.955076 -1.013538  0.594190

In [124]:
df.loc[['w','y']]

a         b         c         d
w  0.760020 -0.300510 -0.023017  0.147757
y  1.550351  0.347815  0.113641  1.080122

In [119]:
df.loc[['w','y'] , ['a','d']]

a         d
w  0.254774  0.642188
y  0.670553  0.102717

In [125]:
df > 0

a      b      c     d
w   True  False  False  True
x   True   True   True  True
y   True   True   True  True
z  False  False  False  True

In [126]:
booldf = df>0

In [127]:
df[booldf]

a         b         c         d
w  0.760020       NaN       NaN  0.147757
x  0.226229  0.730843  0.495561  0.053208
y  1.550351  0.347815  0.113641  1.080122
z       NaN       NaN       NaN  0.594190

In [138]:
df[df['a']>0][['d','c']]

d         c
w  0.147757 -0.023017
x  0.053208  0.495561
y  1.080122  0.113641

In [142]:
df[(df['a']>0) & (df['d']>1)]

a         b         c         d
y  1.550351  0.347815  0.113641  1.080122

In [143]:
df.reset_index()

index         a         b         c         d
0     w  0.760020 -0.300510 -0.023017  0.147757
1     x  0.226229  0.730843  0.495561  0.053208
2     y  1.550351  0.347815  0.113641  1.080122
3     z -0.397774 -0.955076 -1.013538  0.594190

In [144]:
df

a         b         c         d
w  0.760020 -0.300510 -0.023017  0.147757
x  0.226229  0.730843  0.495561  0.053208
y  1.550351  0.347815  0.113641  1.080122
z -0.397774 -0.955076 -1.013538  0.594190

In [146]:
newind = 'RJ WB KL OD'.split()
newind

['RJ', 'WB', 'KL', 'OD']

In [147]:
df['states'] = newind

In [149]:
df.set_index('states')

a         b         c         d
states                                        
RJ      0.760020 -0.300510 -0.023017  0.147757
WB      0.226229  0.730843  0.495561  0.053208
KL      1.550351  0.347815  0.113641  1.080122
OD     -0.397774 -0.955076 -1.013538  0.594190

# Some More DataFrames topics

In [150]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [151]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [153]:
df = pd.DataFrame(np.random.randn(6,2),hier_index,['a','b'])

In [154]:
df

a         b
G1 1  0.500548 -0.172813
   2  0.270135  1.249653
   3 -1.591225  0.120466
G2 1  0.999684 -0.061616
   2  0.762735 -2.673415
   3 -0.926153  1.989112

In [165]:
df.index.names = ['Groups','Num']

In [166]:
df

a         b
Groups Num                    
G1     1    0.500548 -0.172813
       2    0.270135  1.249653
       3   -1.591225  0.120466
G2     1    0.999684 -0.061616
       2    0.762735 -2.673415
       3   -0.926153  1.989112

In [169]:
df.loc['G2'].loc[3]['b']

1.9891118221825117

In [174]:
df.xs(1,level='Num')

a         b
Groups                    
G1      0.500548 -0.172813
G2      0.999684 -0.061616

# Missing Values

In [175]:
this_dist = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[3,6,9]}

In [176]:
df = pd.DataFrame(this_dist)

In [177]:
df

A    B  C
0  1.0  5.0  3
1  2.0  NaN  6
2  NaN  NaN  9

In [178]:
df.dropna()

A    B  C
0  1.0  5.0  3

In [180]:
df.dropna(axis=1, thresh=2)

A  C
0  1.0  3
1  2.0  6
2  NaN  9

In [182]:
df.fillna(value=0)

A    B  C
0  1.0  5.0  3
1  2.0  0.0  6
2  0.0  0.0  9

In [183]:
df

A    B  C
0  1.0  5.0  3
1  2.0  NaN  6
2  NaN  NaN  9

In [185]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Groupby

In [186]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [187]:
df = pd.DataFrame(data)

In [188]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [192]:
dfBy = df.groupby('Company')
dfBy

In [197]:
dfBy.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [199]:
dfBy.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

# Merging, Joining, and Concatenating

In [212]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [213]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [214]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [215]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [216]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [217]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [218]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [219]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

In [220]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [221]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [225]:
pd.merge(left,right,how='inner',on = 'key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [226]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [227]:
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [228]:
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [229]:
pd.merge(left,right, on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [230]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [232]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [233]:
df[df['Sales']>=200]

Company Person  Sales
0    GOOG    Sam    200
2    MSFT    Amy    340
4      FB   Carl    243
5      FB  Sarah    350

In [235]:
def product(x):
    return x*2

8

In [238]:
df['Sales'].apply(product)

0    400
1    240
2    680
3    248
4    486
5    700
Name: Sales, dtype: int64

In [242]:
df['Sales'].apply(lambda x:x*2)

0    400
1    240
2    680
3    248
4    486
5    700
Name: Sales, dtype: int64

In [244]:
df.columns

Index(['Company', 'Person', 'Sales'], dtype='object')

# Input and Output
CSV
HTML
Excel
SQL

In [247]:
pwd

'F:\\Statistics\\miscellaneous'

In [249]:
pd.read_csv('example')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [251]:
data = pd.read_html('https://www.w3schools.com/html/html_tables.asp')

In [257]:
data[0]

Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [5]:
for Number in range (1, 101):
    count = 0
    for i in range(2, (Number//2 + 1)):
        if(Number % i == 0):
            count = count + 1
            break

    if (count == 0 and Number != 1):
        print(Number)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [7]:
a = [True,False]
np.sum(a)

1

In [8]:
def be_friendly(greet = "How are you!", name): pass 

SyntaxError: non-default argument follows default argument (Temp/ipykernel_19584/855280791.py, line 1)

In [10]:
table = np.array([ [1,3], [2,4]])
print(table.max(axis=1)) 

[3 4]


In [13]:
print(lambda x : x*x in range(1,100))

<function <lambda> at 0x0000014DA2427C10>


In [15]:
a = np.array([[1 , 2], [3,4], [5,6]])
c = a[(a > 3) & (a < 11)]
print(c)

[4 5 6]


In [16]:
print ("foo" if (256).bit_length() > 8 else "bar") 

foo


In [18]:
animals = { 'a' : ['ant', 'antelope', 'armadillo'], 'b' : ['beetle', 'bear', 'bat'], 'c' : ['cat', 'cougar', 'camel'] }
animals = defaultdict(list, animals)
print(animals['b'])
print(animals['d']) 

NameError: name 'defaultdict' is not defined